apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${deployment_name}
  labels: 
    app: ${deployment_name}
spec:
  replicas: ${replica_count}
  selector:
    matchLabels:
      app: ${deployment_name}
  template:
    metadata:
      labels:
        app: ${deployment_name}
    spec:
      containers:
      - name: ${deployment_name}
        image: ${image}
        command: ["jupyter"]
        args: ["lab", "--allow-root", "--ip='*'", "--no-browser","--NotebookApp.token=''","--NotebookApp.password=''"]
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: ${deployment_name}
spec:
  selector:
    app: ${deployment_name}
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: LoadBalancer

       
